<a href="<?php echo $this->logURL; ?>">Login/out</a>
<div class="row">
	<div class="span4 offset4">
		<h2>Sign up </h2>
		<fb:login-button  size="medium" max-rows="9" perms="email" >Connect with Facebook</fb:login-button>
	</div>
</div>
<pre>
	<?php print_r($_SESSION); ?>
<?php print_r($this->userObject); ?>
</pre>
<div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId: '<?php echo Josh_Facebook::getAppID() ?>',
          cookie: true,
          xfbml: true,
          oauth: true
        });
        FB.Event.subscribe('auth.login', function(response) {
        	console.log(response);
          window.location = "http://localhost:8080/zf-fb/public";
        });
        FB.Event.subscribe('auth.logout', function(response) {
          //window.location.reload();
        });
      };
      (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());
    </script>