<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<title>ZF Facebook</title>
		<link rel="stylesheet" href="<?php echo $this->baseUrl('css/bootstrap.min.css'); ?>" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('css/style.css'); ?>" />
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			   <div class="navbar-inner">
			     <div class="container">
			       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			         <span class="icon-bar"></span>
			         <span class="icon-bar"></span>
			         <span class="icon-bar"></span>
			       </a>
			       <a class="brand" href="<?php echo $this->baseUrl('/'); ?>">Zend Framework FB</a>
			       <div id="userButton" class="pull-right">
			       	<?php echo $this->userCheck(); ?>
			     </div>
			   </div>
			 </div>
		</div>
		<div class="container">
			<div class="row">
				<div id="messages" class="span4 offset4">
					<?php echo $this->flashAlerts(); ?>
				</div>
			</div>
			<div id="mainContent">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
	<div id="fb-root"></div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
	<script src="//connect.facebook.net/en_US/all.js"></script>
	<script src="<?php echo $this->baseUrl('/js/bootstrap-dropdown.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/bootstrap-alert.js'); ?>"></script>
	<script src='<?php echo $this->baseUrl('/js/zf-ajax.js');?>'></script>
	</body>
</html>