<div id="loginButtons">
	<!--<div class="fb-login-button" data-size="medium" data-scope="email" data-width="200" data-max-rows="1" data-auth-type="fb">Connect with Facebook</div>-->
	<button class="btn fb-button" data-auth-type="fb" ><i class="icon-fb"></i>Facebook(ajax)</button>
	<button class="btn fb-button" data-auth-type="fb-oauth" data-endpoint="<?php echo Josh_Facebook::getLoginUrl(array('redirect_uri' => Zend_Registry::get('config')->facebook->redirectUrl, 'scope' => 'email')); ?>"><i class="icon-fb"></i>Facebook(oauth)</button>
	<button class="btn btn-info" data-auth-type="twitter" data-endpoint="<?php echo Zend_Registry::get('config')->twitter->redirectUrl; ?>"><i class="icon-twitter"></i>Twitter(oauth)</button>
	<button class="btn" data-auth-type="none">No Type (will error)</button>
	<form class="form-inline">
		<input type="text" class="input-small" placeholder="Email">
		<input type="password" class="input-small" placeholder="Password">
		<button type="submit" class="btn" data-auth-type="userpass">Go</button>
	</form>
</div>